name: 'Linear release sync'
description: 'Add release on linear tickets in merged PRs since last release'
author: 'Rayon'


inputs:
  token:
    description: 'Github token'
    required: false
    default: ${{ github.token }}
  linearApiKey:
    description: 'Linear API key'
    required: true
  ticketPrefix:
    default: 'RAY'
    required: false
    description: 'Ticket prefix (can be a regex)'
  comment:
    required: true
    description: 'Comment to add to ticket'



runs:
  using: node20
  main: dist/index.js
